apiVersion: apps/v1
kind: Deployment
metadata:
  name: informer-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: informer
  template:
    metadata:
      labels:
        app: informer
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: informer
        image: kaschaefer/informer:v1alpha4
        ports:
        - containerPort: 8443
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 5
